### ISSUE TITLE
Add support for custom user parameters

### ISSUE THREAD

**Issue by ookami-kb** [andre-paraense/launchdarkly_flutter#19]
**Is your feature request related to a problem? Please describe.**
There's no support for custom user parameters in user builder.

**Describe the solution you'd like**
Add optional parameter e.g. `Map<String, String> custom` to `init` method. It can call corresponding builder methods for Android/iOS sdk:

```java
builder.custom("param", "value")
```

```swift
user.custom = ["param": "value"]
```

**Describe alternatives you've considered**
Nothing I can think of.

**Additional context**
No.

**Comment by andre-paraense** [comment]
Hi, @ookami-kb , thanks for filing this one, we will be looking into it soon, but no time guarantee on this, since we have been quite busy. If you have urgency and feel like contributing, we can accept PRs from you as well. If you can wait, we will be using this issue here to evolve this.

**Comment by ookami-kb** [comment]
Hi, no problem, I will create a PR for that.
