### ISSUE TITLE
Add support for changing user context

### ISSUE THREAD

**Issue by ookami-kb** [andre-paraense/launchdarkly_flutter#24]
**Is your feature request related to a problem? Please describe.**
When your user context is changing (e.g. you need to track logged-in/logged-out users differently, or you have multiple users support) you need to update user in LD. While in iOS SDK you can call `start` again with new user context, Android SDK ignores subsequent calls to `init`.

**Describe the solution you'd like**
Add support for changing user context (available for both [Android](https://docs.launchdarkly.com/sdk/client-side/android#changing-the-user-context) and [iOS](https://docs.launchdarkly.com/sdk/client-side/ios#changing-the-user-context) SDKs).

**Describe alternatives you've considered**
No.

**Additional context**
I can take this issue and prepare a PR.

**Comment by andre-paraense** [comment]
Hey, @ookami-kb , thanks for this one. Are you up to the task? Alright, I will assigned this one to you and wait for your PR. Let me know if you need any support. Cheers!
