### ISSUE TITLE
Android: default rule not setting correct state

### ISSUE THREAD

**Issue by stanojevicboban** [andre-paraense/launchdarkly_flutter#30]
**Describe the bug**
I have a feature flag whose `targeting when off` is set to `false`. I have targeting turned on and have put a specific user ID for whom I want this feature to be enabled. This means that those users should have a value of `true` set for them, and others should get `false`. However, all users (even those specified in targeting) receive `false`. This is occurring only on Android, I am not experiencing this issue on iOS.

**Expected behavior**
Users with specific user ID set in the Targeting should have a `true` set for the FF.

**Desktop (please complete the following information):**
 - OS: Android
 - Version 11

**Comment by andre-paraense** [comment]
Thanks, guys! We will get to it as soon as we can.

Also, we do accept contributions and PRs, if you can get to it faster ;)

**Comment by andre-paraense** [comment]
Hey @stanojevicboban , we have released a new `1.0.2` version and we can't reproduce this issue there. Can you please check it and let us know if it works for you? Cheers!

**Comment by andre-paraense** [comment]
Since we can't reproduce this for now, will close. Let us know if you can still reproduce this in the new version.

**Comment by stanojevicboban** [comment]
@andre-paraense I'm checking in late for this, but I just tested this and can confirm it is working on Android! Thank you for the fix and we can close this off for sure now.
