### ISSUE TITLE
Private User Attributes

### ISSUE THREAD

**Issue by maxlapides** [andre-paraense/launchdarkly_flutter#33]
Thanks so much for the great work on this package! It's very useful :)

**Is your feature request related to a problem? Please describe.**
You may not want to send all attributes back to LaunchDarkly. The security or data protection requirements of your organization may require you to limit what customer or user data is transmitted from your service to a third-party platform like LaunchDarkly.

For example, you may want to target customers by their personally identifying information (PII), such as their email address, without sending the email address to LaunchDarkly.

LaunchDarkly's private user attributes feature lets you choose which attributes get sent back to LaunchDarkly without sacrificing the ability to target user segments. This lets you create targeting rules and segments based on the attributes without having to send sensitive data back to LaunchDarkly.

**Describe the solution you'd like**
Allow configuring private attribute settings in this SDK. Has this feature been considered already?

More details: https://docs.launchdarkly.com/home/users/attributes#creating-private-user-attributes

**Comment by andre-paraense** [comment]
Hey @maxlapides , thanks for your comments.

This feature has yet not been implemented, as you noticed. We will be looking into it sometime in the future. If you need it and would like to contribute with a PR, you are mostly welcome.

Cheers!

**Comment by maxlapides** [comment]
This feature is now merged!
