### ISSUE TITLE
Support multiple environments

### ISSUE THREAD

**Issue by ookami-kb** [andre-paraense/launchdarkly_flutter#37]
**Is your feature request related to a problem? Please describe.**

Currently, there's no way to support multiple requirements available in native SDKs:

- Android: https://docs.launchdarkly.com/sdk/features/multiple-environments#android
- iOS: https://docs.launchdarkly.com/sdk/features/multiple-environments#ios

**Describe the solution you'd like**

Add multiple environments support.

**Describe alternatives you've considered**

No.

**Additional context**

No.

**Comment by ookami-kb** [comment]
We need this for our project, so I can work on this issue if you don't have time for it at the moment.

**Comment by andre-paraense** [comment]
Hi, Kiril, yes, go for it, please, as I don't have much time now.

**Comment by andre-paraense** [comment]
The package has been marked as discontinued and suggested the official package as replacement.
